# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0e\x64\x65mo.inference\"Y\n\x11PredictionRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12/\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x1d.demo.inference.FeatureVector\"@\n\rFeatureVector\x12\x17\n\x0f\x61vg_order_value\x18\x01 \x01(\x01\x12\x16\n\x0emonthly_orders\x18\x02 \x01(\x05\"[\n\x0fPredictionReply\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\r\n\x05label\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t\"J\n\x16\x42\x61tchPredictionRequest\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.demo.inference.PredictionRequest\"L\n\x14\x42\x61tchPredictionReply\x12\x34\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x1f.demo.inference.PredictionReply\"\x14\n\x12HealthCheckRequest\"5\n\x10HealthCheckReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttransport\x18\x02 \x01(\t2\x9a\x02\n\x10InferenceService\x12O\n\x07Predict\x12!.demo.inference.PredictionRequest\x1a\x1f.demo.inference.PredictionReply\"\x00\x12^\n\x0c\x42\x61tchPredict\x12&.demo.inference.BatchPredictionRequest\x1a$.demo.inference.BatchPredictionReply\"\x00\x12U\n\x0bHealthCheck\x12\".demo.inference.HealthCheckRequest\x1a .demo.inference.HealthCheckReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=35
  _globals['_PREDICTIONREQUEST']._serialized_end=124
  _globals['_FEATUREVECTOR']._serialized_start=126
  _globals['_FEATUREVECTOR']._serialized_end=190
  _globals['_PREDICTIONREPLY']._serialized_start=192
  _globals['_PREDICTIONREPLY']._serialized_end=283
  _globals['_BATCHPREDICTIONREQUEST']._serialized_start=285
  _globals['_BATCHPREDICTIONREQUEST']._serialized_end=359
  _globals['_BATCHPREDICTIONREPLY']._serialized_start=361
  _globals['_BATCHPREDICTIONREPLY']._serialized_end=437
  _globals['_HEALTHCHECKREQUEST']._serialized_start=439
  _globals['_HEALTHCHECKREQUEST']._serialized_end=459
  _globals['_HEALTHCHECKREPLY']._serialized_start=461
  _globals['_HEALTHCHECKREPLY']._serialized_end=514
  _globals['_INFERENCESERVICE']._serialized_start=517
  _globals['_INFERENCESERVICE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
